### ISSUE TITLE
Refactor Application class to use the correct code style

### ISSUE THREAD

**Issue by TheSharpOwl** [TheSharpOwl/Mizu#25]
1. The code style used can be found [here](https://github.com/TheSharpOwl/Mizu/wiki/Code-Style). 
2. Remove this `TODO` in `Application.hpp` after you are done 
```cpp
// TODO refactor function names to use lowerCamelCase not UpperCamelCase
```

**Comment by lodenrogue** [comment]
Don't you have some automated tools that will auto refactor your code?

**Comment by TheSharpOwl** [comment]
1. I don't know any free tools for refactoring the code for such situation (I mean I just know that I have to refactor variables on by one, right click -> refactor -> rename or something like this but to run some tool that will fix it all at once like `clang-format` fixing all the format related stuff, then I don't know (especially on Windows)
2. I can do it easily but I just wanted to put it here for people who are new to contribution and wanna find easy issues to get started with

**Comment by lodenrogue** [comment]
I think this is a great first issue for someone new to the project. Most IDEs have an auto format feature. Some even have the ability to add custom format rules.
